### ISSUE TITLE
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'builtin_function_or_method'

### ISSUE THREAD

**Issue by txw226** [krichelj/PyDiffGame#16]
I get this error when running any of the examples out of the box with Python 3.9.21:
`Traceback (most recent call last):
  File "/home/twheeler/gitrepos/jim/pydiff/lqr_tutorial.py", line 9, in <module>
    from PyDiffGame.PyDiffGameLQRComparison import PyDiffGameLQRComparison
  File "/home/twheeler/anaconda3/envs/jim/lib/python3.9/site-packages/PyDiffGame/PyDiffGameLQRComparison.py", line 14, in <module>
    from PyDiffGame.ContinuousPyDiffGame import ContinuousPyDiffGame
  File "/home/twheeler/anaconda3/envs/jim/lib/python3.9/site-packages/PyDiffGame/ContinuousPyDiffGame.py", line 13, in <module>
    class ContinuousPyDiffGame(PyDiffGame):
  File "/home/twheeler/anaconda3/envs/jim/lib/python3.9/site-packages/PyDiffGame/ContinuousPyDiffGame.py", line 33, in ContinuousPyDiffGame
    P_f: Optional[Sequence[np.array] | np.array] = None,
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'builtin_function_or_method'
`
If you're using Python >=3.10 you should not get this error, but if you're using Python 3.9 like me, I fixed it by changing ContinuousPyDiffGame.py line 33 from `P_f: Optional[Sequence[np.array] | np.array] = None,` to `P_f: Union[Sequence[np.array], np.array] = None`. See explanation here: https://stackoverflow.com/questions/76712720/typeerror-unsupported-operand-types-for-type-and-nonetype

**Comment by krichelj** [comment]
Will work on a fix. Could you share the code you are running in `lqr_tutorial.py`?

**Comment by krichelj** [comment]
Fixed in 05766f6e4a722ea4b8e2e36827fccaff5d225750.
